#ifndef DISPATCH_H
#define DISPATCH_H


#include "Iter.h"
#include "dtypes.h"
#include "Backend.h"
#include "register.h"
#include "helpers.h"

#define n_of_non_cast 19

typedef enum {
    KERNEL_ADD = 0, 
    KERNEL_SUBTRACT,
    KERNEL_MULTIPLY,
    KERNEL_DIVIDE,
    KERNEL_SQUARE_ROOT,
    KERNEL_ABSOLUTE_VALUE,
    KERNEL_NEGATION,
    KERNEL_POWER,
    KERNEL_EQUALITY,
    KERNEL_GREATER_THAN,
    KERNEL_LESS_THAN,
    KERNEL_ELEMENT_WISE_MAXIMUM,
    KERNEL_ELEMENT_WISE_MINIMUM,
    KERNEL_WHERE,
    KERNEL_ZEROS,
    KERNEL_ONES,
    KERNEL_FILL,
    KERNEL_SUM_REDUCTION,
    KERNEL_MAX_REDUCTION,
    KERNEL_MIN_REDUCTION,
    KERNEL_ARGMAX_REDUCTION,
    KERNEL_ARGMIN_REDUCTION,
    KERNEL_LOG,
    KERNEL_EXP,
    KERNEL_MATMUL,


    KERNEL_ADD_BACKWARDS,
    KERNEL_SUBTRACT_BACKWARDS,
    KERNEL_MULTIPLY_BACKWARDS,
    KERNEL_DIVIDE_BACKWARDS,
    KERNEL_SQUARE_ROOT_BACKWARDS,
    KERNEL_ABSOLUTE_VALUE_BACKWARDS,
    KERNEL_NEGATION_BACKWARDS,
    KERNEL_POWER_BACKWARDS,
    KERNEL_GREATER_THAN_BACKWARDS,
    KERNEL_LESS_THAN_BACKWARDS,
    KERNEL_ELEMENT_WISE_MAXIMUM_BACKWARDS,
    KERNEL_ELEMENT_WISE_MINIMUM_BACKWARDS,
    KERNEL_WHERE_BACKWARDS,
    KERNEL_ZEROS_BACKWARDS,
    KERNEL_ONES_BACKWARDS,
    KERNEL_FILL_BACKWARDS,
    KERNEL_SUM_REDUCTION_BACKWARDS,
    KERNEL_MAX_REDUCTION_BACKWARDS,
    KERNEL_MIN_REDUCTION_BACKWARDS,
    KERNEL_LOG_BACKWARDS,
    KERNEL_EXP_BACKWARDS,


    KERNEL_I8_TO_I16,
    KERNEL_I8_TO_I32,
    KERNEL_I8_TO_I64,
    KERNEL_I8_TO_U8,
    KERNEL_I8_TO_U16,
    KERNEL_I8_TO_U32,
    KERNEL_I8_TO_U64,
    KERNEL_I8_TO_F32,
    KERNEL_I8_TO_F64,
    KERNEL_I8_TO_BOOL,


    KERNEL_I16_TO_I8,
    KERNEL_I16_TO_I32,
    KERNEL_I16_TO_I64,
    KERNEL_I16_TO_U8,
    KERNEL_I16_TO_U16,
    KERNEL_I16_TO_U32,
    KERNEL_I16_TO_U64,
    KERNEL_I16_TO_F32,
    KERNEL_I16_TO_F64,
    KERNEL_I16_TO_BOOL,

    KERNEL_I32_TO_I8,
    KERNEL_I32_TO_I16,
    KERNEL_I32_TO_I64,
    KERNEL_I32_TO_U8,
    KERNEL_I32_TO_U16,
    KERNEL_I32_TO_U32,
    KERNEL_I32_TO_U64,
    KERNEL_I32_TO_F32,
    KERNEL_I32_TO_F64,
    KERNEL_I32_TO_BOOL,

    KERNEL_I64_TO_I8,
    KERNEL_I64_TO_I16,
    KERNEL_I64_TO_I32,
    KERNEL_I64_TO_U8,
    KERNEL_I64_TO_U16,
    KERNEL_I64_TO_U32,
    KERNEL_I64_TO_U64,
    KERNEL_I64_TO_F32,
    KERNEL_I64_TO_F64,
    KERNEL_I64_TO_BOOL,

    KERNEL_U8_TO_I8,
    KERNEL_U8_TO_I16, 
    KERNEL_U8_TO_I32, 
    KERNEL_U8_TO_I64,
    KERNEL_U8_TO_U16,
    KERNEL_U8_TO_U32,
    KERNEL_U8_TO_U64,
    KERNEL_U8_TO_F32,
    KERNEL_U8_TO_F64,
    KERNEL_U8_TO_BOOL,

    KERNEL_U16_TO_I8,
    KERNEL_U16_TO_I16,
    KERNEL_U16_TO_I32,
    KERNEL_U16_TO_I64,
    KERNEL_U16_TO_U8,
    KERNEL_U16_TO_U32,
    KERNEL_U16_TO_U64,
    KERNEL_U16_TO_F32,
    KERNEL_U16_TO_F64,
    KERNEL_U16_TO_BOOL,


    KERNEL_U32_TO_I8,
    KERNEL_U32_TO_I16,
    KERNEL_U32_TO_I32,
    KERNEL_U32_TO_I64,
    KERNEL_U32_TO_U8,
    KERNEL_U32_TO_U16,
    KERNEL_U32_TO_U64,
    KERNEL_U32_TO_F32,
    KERNEL_U32_TO_F64,
    KERNEL_U32_TO_BOOL,

    KERNEL_U64_TO_I8,
    KERNEL_U64_TO_I16,
    KERNEL_U64_TO_I32,
    KERNEL_U64_TO_I64,
    KERNEL_U64_TO_U8,
    KERNEL_U64_TO_U16,
    KERNEL_U64_TO_U32,
    KERNEL_U64_TO_U64,
    KERNEL_U64_TO_F32,
    KERNEL_U64_TO_F64,
    KERNEL_U64_TO_BOOL,

   
    KERNEL_F32_TO_I8,
    KERNEL_F32_TO_I16,
    KERNEL_F32_TO_I32,
    KERNEL_F32_TO_I64,
    KERNEL_F32_TO_U8,
    KERNEL_F32_TO_U16,
    KERNEL_F32_TO_U32,
    KERNEL_F32_TO_U64,
    KERNEL_F32_TO_F64,
    KERNEL_F32_TO_BOOL,

    KERNEL_F64_TO_I8,
    KERNEL_F64_TO_I16,
    KERNEL_F64_TO_I32,
    KERNEL_F64_TO_I64,
    KERNEL_F64_TO_U8,
    KERNEL_F64_TO_U16,
    KERNEL_F64_TO_U32,
    KERNEL_F64_TO_U64,
    KERNEL_F64_TO_F32,
    KERNEL_F64_TO_BOOL,


    KERNEL_BOOL_TO_I8,
    KERNEL_BOOL_TO_I16,
    KERNEL_BOOL_TO_I32,
    KERNEL_BOOL_TO_I64,
    KERNEL_BOOL_TO_U8,
    KERNEL_BOOL_TO_U16,
    KERNEL_BOOL_TO_U32,
    KERNEL_BOOL_TO_U64,
    KERNEL_BOOL_TO_F32,
    KERNEL_BOOL_TO_F64,

    KERNEL_COUNT
} kernel_id;


bool dispatch_register_kernel(dtype type, Backend backend, kernel_id kernel,  kernel_fn fn);

bool dispatch_get_kernel(kernel_fn *fn, dtype type, Backend backend, kernel_id kernel);



#endif // DISPATCH_H